### ISSUE TITLE
Nextcloud Nemo plugin integration

### ISSUE THREAD

**Issue by jisse44** [tpokorra/lbs-nextcloud#1]
Hi,
In the nextcloud-client-nemo package, you forget to change the appname from 'ownCloud' to 'Nextcloud'  in syncstate.py, line 28.

Thanks for the Fedora support and packaging

**Comment by tpokorra** [comment]
@jisse44, thanks for reporting this! I am just rebuilding the packages at https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/, and have added a pull request to upstream nextcloud client too!
