### ISSUE TITLE
nextcloud-client-dolphin should require nextcloud-client

### ISSUE THREAD

**Issue by digver** [tpokorra/lbs-nextcloud#2]
Hey Timotheus, I appreciate your COPR for the nextcloud client.

I expected nextcloud-client-dolphin to require nextcloud-client.

Shouldn't there be something like
`
Requires: %{name}-client
`
be included in the nextcloud-client.spec section for dolphin?

**Comment by tpokorra** [comment]
@digver, thank you for your suggestion!

I don't know the answer. I am using the spec from http://pkgs.fedoraproject.org/cgit/rpms/owncloud-client.git/tree/owncloud-client.spec and just modified it to work for nextcloud-client.

I am wondering if nextcloud-client-dolphin should require nextcloud-client or nextcloud-client-lib? Could you please try whether nextcloud-client-lib is sufficient?

**Comment by digver** [comment]
I can try it with just  nextcloud-client-lib later today. But I think my reasoning was the extensions aren't of much use without the ability to set up an account to sync with. 

I guess it's possible to have different sync-clients, in which case you wouldn't want to require a particular one by requiring it. But then I guess you could include "provides" in the specs for the sync-clients. 

My rpm building skills are very weak, so maybe I'm thinking about it the wrong way...

**Comment by digver** [comment]
@tpokorra I took a look using ldd and it doesn't look like nextcloud-client-dolphin needs nextcloud-client-libs. 

So, it seems like requiring nextcloud-client is a matter of making it usable. I have no idea though what best practice is for using "Requires" in the spec.

**Comment by tpokorra** [comment]
@digver thanks for investigating this! I will push the fix, and will rebuild the packages in the copr https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/
