### ISSUE TITLE
nothing provides nextcloud-client-(x86-64)

### ISSUE THREAD

**Issue by yrubdarb** [tpokorra/lbs-nextcloud#3]
#dnf upgrade -b 
Last metadata expiration check: 0:08:43 ago on Sat Nov  5 06:13:18 2016.
Error: nothing provides nextcloud-client-(x86-64) = 2.2.4-3.fc24 needed by nextcloud-client-nautilus-2.2.4-3.fc24.x86_64

rpm -qa | grep nextcloud
nextcloud-client-2.2.4-3.fc24.x86_64
nextcloud-client-libs-2.2.4-3.fc24.x86_64
nextcloud-client-nautilus-2.2.4-2.fc24.x86_64

**Comment by tpokorra** [comment]
thanks for reporting this! there are updated builds now in the copr repo https://copr.fedorainfracloud.org/coprs/tpokorra/nextcloud/
